### ISSUE TITLE
kernel crash when restarting mhvtl.target

### ISSUE THREAD

**Issue by rohr22** [markh794/mhvtl#131]
On a RHEL9.2 x86_64 machine, I encountered a kernel crash from mhvtl and system reboot while running `systemctl restart mhvtl.target`. I ran the crash tools against the resulting vmcore file and it showed:

```
      KERNEL: vmlinux  [TAINTED]                
    DUMPFILE: vmcore  [PARTIAL DUMP]
        CPUS: 8
        DATE: Sun May 12 15:15:09 CDT 2024
      UPTIME: 8 days, 20:55:19
LOAD AVERAGE: 0.00, 0.00, 0.00
       TASKS: 498
    NODENAME: testfourx86-rh9.hpsslab.ibm.com
     RELEASE: 5.14.0-284.11.1.el9_2.x86_64
     VERSION: #1 SMP PREEMPT_DYNAMIC Wed Apr 12 10:45:03 EDT 2023
     MACHINE: x86_64  (2394 Mhz)
      MEMORY: 16 GB
       PANIC: "Oops: 0000 [#1] PREEMPT SMP PTI" (check log for details)
         PID: 117311
     COMMAND: "vtltape"
        TASK: ffff9cc206f7c700  [THREAD_INFO: ffff9cc206f7c700]
         CPU: 4
       STATE: TASK_RUNNING (PANIC)

crash> bt
PID: 117311   TASK: ffff9cc206f7c700  CPU: 4    COMMAND: "vtltape"
 #0 [ffffaad8c78fbb70] machine_kexec at ffffffff8906c237
 #1 [ffffaad8c78fbbc8] __crash_kexec at ffffffff891c3c9a
 #2 [ffffaad8c78fbc88] crash_kexec at ffffffff891c4e58
 #3 [ffffaad8c78fbc90] oops_end at ffffffff890291db
 #4 [ffffaad8c78fbcb0] page_fault_oops at ffffffff8907bc5b
 #5 [ffffaad8c78fbd08] exc_page_fault at ffffffff89b286d2
 #6 [ffffaad8c78fbd30] asm_exc_page_fault at ffffffff89c00b62
    [exception RIP: scsi_remove_device+11]
    RIP: ffffffff897701ab  RSP: ffffaad8c78fbde8  RFLAGS: 00010202
    RAX: 000000000000000d  RBX: ffff9cbeffa2b9c0  RCX: 0000000000000000
    RDX: ffff9cbeffa2b9c0  RSI: ffff9cbeffa2bf00  RDI: 0000000000000000
    RBP: 0000000000000000   R8: ffff9cbec2b65e40   R9: 0000000000000001
    R10: 0000000000000001  R11: 0000000000000000  R12: 0000000000000000
    R13: 000000000000000d  R14: ffff9cbec0f16010  R15: dead000000000100
    ORIG_RAX: ffffffffffffffff  CS: 0010  SS: 0018
 #7 [ffffaad8c78fbdf8] mhvtl_remove_lu at ffffffffc0a94584 [mhvtl]
 #8 [ffffaad8c78fbe48] mhvtl_c_ioctl at ffffffffc0a94837 [mhvtl]
 #9 [ffffaad8c78fbe68] __x64_sys_ioctl at ffffffff893df1b7
#10 [ffffaad8c78fbe98] do_syscall_64 at ffffffff89b25159
#11 [ffffaad8c78fbeb8] do_syscall_64 at ffffffff89b25169
#12 [ffffaad8c78fbed8] do_syscall_64 at ffffffff89b25169
#13 [ffffaad8c78fbef0] syscall_exit_work at ffffffff89197d6a
#14 [ffffaad8c78fbf28] exc_page_fault at ffffffff89b286d2
#15 [ffffaad8c78fbf50] entry_SYSCALL_64_after_hwframe at ffffffff89c0009b
    RIP: 00007ffff7c3ec6b  RSP: 00007fffffffe948  RFLAGS: 00000206
    RAX: ffffffffffffffda  RBX: 00000000fffffffe  RCX: 00007ffff7c3ec6b
    RDX: 00007fffffffe974  RSI: 0000000000000205  RDI: 0000000000000003
    RBP: 000000000000c350   R8: 000000000043fbd0   R9: 0000000000000000
    R10: 00007ffff7c11d78  R11: 0000000000000206  R12: 0000000000000001
    R13: 0000000000000003  R14: 00007fffffffeed6  R15: 0000000000000003
    ORIG_RAX: 0000000000000010  CS: 0033  SS: 002b
```

This crash has occurred at least two different times.

**Comment by rohr22** [comment]
This is with the commit for "vtltape LP 0x11: Only update load status once per change." 
 (8a88fa87861411e46782dd711e3be5a7c4bbbbbb)

**Comment by markh794** [comment]
Looking into it..
mhvtl_remove_lu() calls the sci_remove_device() in the scsi mid layer.

**Comment by markh794** [comment]
testing a patch at the moment.
The issue appears to be if you start a target and stop within a short window. While the user-space daemon stops sending op codes to the target, the kernel st & mid-layer send various inquiry/mode select pages and if the daemon is stopped while these commands are still in flight, we get the panic.

**Comment by markh794** [comment]
Commit 3a8085ec846714c11d6f4ee72d30197981c748b1 should resolve this issue.
Previously, there was no check to ensure all OP codes were complete before exiting.

**Comment by rohr22** [comment]
Thank you very much for making these changes! I'll try to build with this code and provide you feedback soon.

**Comment by markh794** [comment]
FWIW: I have run multiple concurrent loops of

for a in $(seq 1 100)
do
vtltape -q 11 -v
vtlcmd 11 exit
done

Hopefully it will work out for you too :)

**Comment by rohr22** [comment]
It looks like the code may still have issues, although maybe it should be lower priority. I ran this:

```
for i in {1..25}; do
       	systemctl restart mhvtl.target
done
```

And it generated a kernel dump and rebooted the machine. I ran `crash vmcore vmlinux` and saw:
```
      KERNEL: vmlinux  [TAINTED]                
    DUMPFILE: vmcore  [PARTIAL DUMP]
        CPUS: 8
        DATE: Tue May 28 11:16:39 CDT 2024
      UPTIME: 11 days, 14:50:25
LOAD AVERAGE: 11.58, 11.20, 6.51
       TASKS: 642
    NODENAME: testtwox86-rh9.hpsslab.ibm.com
     RELEASE: 5.14.0-284.11.1.el9_2.x86_64
     VERSION: #1 SMP PREEMPT_DYNAMIC Wed Apr 12 10:45:03 EDT 2023
     MACHINE: x86_64  (2394 Mhz)
      MEMORY: 16 GB
       PANIC: "Oops: 0000 [#1] PREEMPT SMP PTI" (check log for details)
         PID: 51430
     COMMAND: "vtltape"
        TASK: ffff9f719469a380  [THREAD_INFO: ffff9f719469a380]
         CPU: 3
       STATE: TASK_RUNNING (PANIC)

crash> bt
PID: 51430    TASK: ffff9f719469a380  CPU: 3    COMMAND: "vtltape"
 #0 [ffffbbf342b93be0] machine_kexec at ffffffff9966c237
 #1 [ffffbbf342b93c38] __crash_kexec at ffffffff997c3c9a
 #2 [ffffbbf342b93cf8] crash_kexec at ffffffff997c4e58
 #3 [ffffbbf342b93d00] oops_end at ffffffff996291db
 #4 [ffffbbf342b93d20] page_fault_oops at ffffffff9967bc5b
 #5 [ffffbbf342b93d78] exc_page_fault at ffffffff9a1286d2
 #6 [ffffbbf342b93da0] asm_exc_page_fault at ffffffff9a200b62
    [exception RIP: scsi_remove_device+11]
    RIP: ffffffff99d701ab  RSP: ffffbbf342b93e58  RFLAGS: 00010202
    RAX: 0000000000000011  RBX: ffff9f7180ae1240  RCX: 0000000000000000
    RDX: ffff9f7180ae1240  RSI: ffff9f721ada2780  RDI: 0000000000000000
    RBP: 0000000000000000   R8: ffff9f7182b87e40   R9: 0000000000000001
    R10: 0000000000000001  R11: 0000000000000000  R12: 0000000000000000
    R13: 0000000000000011  R14: ffff9f71855de410  R15: dead000000000100
    ORIG_RAX: ffffffffffffffff  CS: 0010  SS: 0018
 #7 [ffffbbf342b93e68] mhvtl_remove_lu at ffffffffc0b77584 [mhvtl]
 #8 [ffffbbf342b93eb8] mhvtl_c_ioctl at ffffffffc0b77837 [mhvtl]
 #9 [ffffbbf342b93ed8] __x64_sys_ioctl at ffffffff999df1b7
#10 [ffffbbf342b93f08] do_syscall_64 at ffffffff9a125159
#11 [ffffbbf342b93f20] do_syscall_64 at ffffffff9a125169
#12 [ffffbbf342b93f50] entry_SYSCALL_64_after_hwframe at ffffffff9a20009b
    RIP: 00007ffff7c3ec6b  RSP: 00007fffffffe938  RFLAGS: 00000246
    RAX: ffffffffffffffda  RBX: 0000000000000000  RCX: 00007ffff7c3ec6b
    RDX: 00007fffffffe974  RSI: 0000000000000205  RDI: 0000000000000004
    RBP: 0000000000435ae0   R8: 00000000004401a0   R9: 0000000000000000
    R10: 0000000000004000  R11: 0000000000000246  R12: 0000000000000000
    R13: 0000000000000000  R14: 0000000000000011  R15: 0000000000000004
    ORIG_RAX: 0000000000000010  CS: 0033  SS: 002b

```

The code seems to work well when just doing a `systemctl restart mhvtl.target` by itself. However, if you try to break it with multiple of these back to back, it seems like it is still breakable.

**Comment by rohr22** [comment]
It looks like it may crash with:

`systemctl restart mhvtl.target`

wait a couple seconds
`systemctl restart mhvtl.target`

**Comment by wangshq1990** [comment]
I encountered the same crash. I compiled and ran commit version 8d49fba, but the issue still persists. Is there any new progress on this issue?  Please let me know. Thank you.
